name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.config.name }} | ${{ matrix.config.build_type }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Super Mario Bros. X - macOS",
            os: macos-latest,
            extra_options: "-DTHEXTECH_PRELOAD_ENVIRONMENT=\"`pwd`/assets/\" -DTHEXTECH_CUSTOM_ICON_PATH=\"`pwd`/assets/graphics/ui/icon/smbx.icns\" -DTHEXTECH_ICON_NAME=smbx.icns -DTHEXTECH_BUNDLE_NAME=\"Super Mario Bros. X\" -DTHEXTECH_EXECUTABLE_NAME=\"thextech\"",
            deps_cmdline: "brew install ninja wget p7zip lftp",
            build_type: "MinSizeRel",
            assets_url: "https://wohlsoft.ru/TheXTech/_downloads/thextech-smbx13-assets-full.7z",
            package_filename: "thextech-super-mario-bros-x-dev.dmg",
            upload_directory: "www/macosx/"
          }
        - {
            name: "Super Mario Bros. X - Ubuntu 16.04",
            os: ubuntu-16.04,
            extra_options: "-DUSE_STATIC_LIBC=ON -DUSE_SYSTEM_LIBS=OFF -DUSE_SYSTEM_SDL2=OFF -DUSE_SHARED_FREEIMAGE=OFF -DPGE_SHARED_SDLMIXER=OFF",
            deps_cmdline: "sudo apt-get update -qq && sudo apt-get install -qq cmake ninja-build cmake ninja-build lftp \"^libxcb.*\" libx11-dev libx11-xcb-dev libgtk-3-dev libgegl-dev libxcursor-dev libxrender-dev libxrandr-dev libxext-dev libxi-dev libxss-dev libxt-dev libxv-dev libxxf86vm-dev libxinerama-dev libxkbcommon-dev libfontconfig1-dev libasound2-dev libpulse-dev libdbus-1-dev udev mtdev-tools webp libudev-dev libglm-dev libwayland-dev libegl1-mesa-dev mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev libgles2-mesa libgles2-mesa-dev libmirclient-dev libproxy-dev",
            build_type: "MinSizeRel",
            assets_url: "https://wohlsoft.ru/TheXTech/_downloads/thextech-smbx13-assets-full.7z",
            subdir_name: "thextech-super-mario-bros-x",
            package_filename: "thextech-super-mario-bros-x-ubuntu-16-04-dev.tar.gz",
            upload_directory: "www/ubuntu-16-04/"
          }
        - {
            name: "Super Mario Bros. X - Ubuntu 18.04",
            os: ubuntu-18.04,
            extra_options: "-DUSE_STATIC_LIBC=ON -DUSE_SYSTEM_LIBS=OFF -DUSE_SYSTEM_SDL2=OFF -DUSE_SHARED_FREEIMAGE=OFF -DPGE_SHARED_SDLMIXER=OFF",
            deps_cmdline: "sudo apt-get update -qq && sudo apt-get install -qq cmake ninja-build cmake ninja-build lftp \"^libxcb.*\" libx11-dev libx11-xcb-dev libgtk-3-dev libgegl-dev libxcursor-dev libxrender-dev libxrandr-dev libxext-dev libxi-dev libxss-dev libxt-dev libxv-dev libxxf86vm-dev libxinerama-dev libxkbcommon-dev libfontconfig1-dev libasound2-dev libpulse-dev libdbus-1-dev udev mtdev-tools webp libudev-dev libglm-dev libwayland-dev libegl1-mesa-dev mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev libgles2-mesa libgles2-mesa-dev libmirclient-dev libproxy-dev",
            build_type: "MinSizeRel",
            assets_url: "https://wohlsoft.ru/TheXTech/_downloads/thextech-smbx13-assets-full.7z",
            subdir_name: "thextech-super-mario-bros-x",
            package_filename: "thextech-super-mario-bros-x-ubuntu-18-04-dev.tar.gz",
            upload_directory: "www/ubuntu-18-04/"
          }
        - {
            name: "Super Mario Bros. X - Ubuntu 20.04",
            os: ubuntu-20.04,
            extra_options: "-DUSE_STATIC_LIBC=ON -DUSE_SYSTEM_LIBS=OFF -DUSE_SYSTEM_SDL2=OFF -DUSE_SHARED_FREEIMAGE=OFF -DPGE_SHARED_SDLMIXER=OFF",
            deps_cmdline: "sudo apt-get update -qq && sudo apt-get install -qq cmake ninja-build cmake ninja-build lftp \"^libxcb.*\" libx11-dev libx11-xcb-dev libgtk-3-dev libgegl-dev libxcursor-dev libxrender-dev libxrandr-dev libxext-dev libxi-dev libxss-dev libxt-dev libxv-dev libxxf86vm-dev libxinerama-dev libxkbcommon-dev libfontconfig1-dev libasound2-dev libpulse-dev libdbus-1-dev udev mtdev-tools webp libudev-dev libglm-dev libwayland-dev libegl1-mesa-dev mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev libgles2-mesa libgles2-mesa-dev libmirclient-dev libproxy-dev",
            build_type: "MinSizeRel",
            assets_url: "https://wohlsoft.ru/TheXTech/_downloads/thextech-smbx13-assets-full.7z",
            subdir_name: "thextech-super-mario-bros-x",
            package_filename: "thextech-super-mario-bros-x-ubuntu-20-04--dev.tar.gz",
            upload_directory: "www/ubuntu-20-04/"
          }

    steps:
    - uses: actions/checkout@v1

    - name: Install Dependencies
      shell: bash
      run: |
        if [[ ! -z "${{ matrix.config.deps_cmdline }}" ]]; then
          eval ${{ matrix.config.deps_cmdline }}
        fi
        # Pull submodules
        git submodule init
        git submodule update

    - name: Download assets
      shell: bash
      run: |
        wget "${{ matrix.config.assets_url }}" -O assets.7z
        mkdir -p assets
        cd assets
        7z x ../assets.7z
        cd ..
        rm assets.7z

    - name: Configure
      shell: bash
      run: |
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} ${{ matrix.config.extra_options }} .

    - name: Build
      shell: bash
      run: |
        export MAKEFLAGS=--keep-going
        cmake --build build --config ${{ matrix.config.build_type }} --parallel 3

    - name: List dependent libraries
      if: runner.os == 'Linux'
      shell: bash
      run: |
        file build/output/bin/thextech
        ldd build/output/bin/thextech

    - name: Create Package
      if: runner.os == 'macOS' || runner.os == 'Linux'  # Remove to make packages of all targets
      shell: bash
      run: |
        cd build
        mkdir package
        if [[ "${{ runner.os }}" == 'Windows' ]]; then
          echo "WIP"
        elif [[ "${{ runner.os }}" == 'macOS' ]]; then
          cpack
          mv *.dmg package/${{ matrix.config.package_filename }}
        elif [[ "${{ runner.os }}" == 'Linux' ]]; then
          mkdir "package/${{ matrix.config.subdir_name }}"
          cp output/bin/thextech "package/${{ matrix.config.subdir_name }}/thextech"
          cp -r ../assets/* "package/${{ matrix.config.subdir_name }}/"
          cd package
          tar -cvzf "${{ matrix.config.package_filename }}" "${{ matrix.config.subdir_name }}"
          rm -Rf "${{ matrix.config.subdir_name }}"
          cd ..
        fi
        cd ..

    - name: Upload artifact
      if: runner.os == 'macOS' || runner.os == 'Linux'  # Remove to store packages of all targets
      uses: actions/upload-artifact@v2
      with:
        path: build/package/${{ matrix.config.package_filename }}
        name: ${{ matrix.config.name }} ${{ matrix.config.build_type }}

    - name: Deploy to builds.wohlsoft.ru
      if: runner.os == 'macOS' || runner.os == 'Linux'
      shell: bash
      run: |
        UPLOAD_LIST="set ssl:verify-certificate no;"
        UPLOAD_LIST="${UPLOAD_LIST} put -O ${{ matrix.config.upload_directory }} ./build/package/${{ matrix.config.package_filename }};"
        lftp -e "${UPLOAD_LIST} exit" -u ${{ secrets.builds_login }},${{ secrets.builds_password }} ${{ secrets.builds_host }}

    - name: List Build Directory
      if: always()
      shell: bash
      run: |
        git status
        ls -lR build
